version: '3.8'

services:
  vue-app:
    build:
      context: .  
    container_name: vue-app
    ports:
      - "8080:8080"
    networks:
      - vue-net
    volumes:
      - ./src:/usr/src/app/src 

networks:
  vue-net:
    driver: bridge
